# 开发环境配置
server:
  port: 8080

spring:
  application:
    name: rui-demo-web

# 禁用不需要的功能
rui:
  monitoring:
    enabled: false
  security:
    enabled: false
  tracing:
    enabled: false
  log:
    enabled: false

# 禁用Spring Boot Actuator
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: false
  metrics:
    export:
      enabled: false

# 日志配置
logging:
  level:
    com.rui: DEBUG
    org.springframework: INFO